# Reference:
# https://github.com/aelsabbahy/goss/blob/master/docs/manual.md

file:
  # API Binary
  /home/api/api:
    exists: true
    mode: "0755"
    filetype: file
  # Statically Compile Assets
  /home/api/ui/index.html:
    exists: true
    mode: "0644"
    filetype: file
  /home/api/ui/assets/application.js:
    exists: true
    mode: "0644"
    filetype: file
port:
  # TCP/HTTP Port
  tcp:8000:
    listening: true
    ip:
    - 0.0.0.0
process:
  # API process
  api:
    running: true
http:
  # Application root endpoint
  http://localhost:8000:
    status: 200
    timeout: 1000
  # TODO add http health route check
